default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   database: rails_development
   username: myapp
   password: root

test:
   adapter: postgresql
   encoding: unicode
   database: railsapp_test
   username: myapp
   password: root
 
production:
   adapter: postgresql
   encoding: unicode
   database: railsapp_production
   username: myapp
   password: root